import { Service } from "@/app/services/page";

export const servicesData: Service[] = [
  {
    ServiceID: 201,
    ServiceName: "Basic Cleaning",
    Description: "Standard home cleaning service",
    Category: "Cleaning",
    Price: 50,
    Duration: 90,
    ProviderID: 102,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 202,
    ServiceName: "Deep Cleaning",
    Description: "Thorough cleaning including windows & vents",
    Category: "Cleaning",
    Price: 100,
    Duration: 180,
    ProviderID: 102,
    Image: "Deep-Cleaning.png",
  },
  {
    ServiceID: 203,
    ServiceName: "Lawn Mowing",
    Description: "Basic lawn care and mowing",
    Category: "Gardening",
    Price: 40,
    Duration: 60,
    ProviderID: 103,
    Image: "Lawn-Mowing.png",
  },
  {
    ServiceID: 204,
    ServiceName: "Tree Trimming",
    Description: "Trimming and pruning of trees and bushes",
    Category: "Gardening",
    Price: 75,
    Duration: 120,
    ProviderID: 103,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 205,
    ServiceName: "Home Repair",
    Description: "General handyman repairs",
    Category: "Handyman",
    Price: 60,
    Duration: 60,
    ProviderID: 104,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 206,
    ServiceName: "Furniture Assembly",
    Description: "Assembly of household furniture",
    Category: "Handyman",
    Price: 45,
    Duration: 90,
    ProviderID: 104,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 207,
    ServiceName: "Tech Support",
    Description: "Setup and troubleshooting",
    Category: "IT Support",
    Price: 80,
    Duration: 60,
    ProviderID: 105,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 208,
    ServiceName: "Virus Removal",
    Description: "Removing viruses and malware",
    Category: "IT Support",
    Price: 70,
    Duration: 120,
    ProviderID: 105,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 209,
    ServiceName: "Plumbing Fixes",
    Description: "Small plumbing repairs",
    Category: "Plumbing",
    Price: 90,
    Duration: 60,
    ProviderID: 106,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 210,
    ServiceName: "Pipe Installation",
    Description: "Installing and replacing pipes",
    Category: "Plumbing",
    Price: 120,
    Duration: 180,
    ProviderID: 106,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 211,
    ServiceName: "Window Cleaning",
    Description: "Cleaning exterior and interior windows",
    Category: "Cleaning",
    Price: 60,
    Duration: 90,
    ProviderID: 107,
    Image: "Window-Cleaning.png",
  },
  {
    ServiceID: 212,
    ServiceName: "Power Washing",
    Description: "High-pressure washing for surfaces",
    Category: "Cleaning",
    Price: 110,
    Duration: 120,
    ProviderID: 107,
    Image: "Power-Washingpng",
  },
  {
    ServiceID: 213,
    ServiceName: "Electrical Repairs",
    Description: "Fixing basic electrical issues",
    Category: "Electrical",
    Price: 95,
    Duration: 90,
    ProviderID: 108,
    Image: "Electrical-Repairs.png",
  },
  {
    ServiceID: 214,
    ServiceName: "Wiring Installation",
    Description: "New wiring and rewiring services",
    Category: "Electrical",
    Price: 150,
    Duration: 240,
    ProviderID: 108,
    Image: "Wiring-Installation.png",
  },
  {
    ServiceID: 215,
    ServiceName: "Interior Design",
    Description: "Design consulting for home interiors",
    Category: "Interior Design",
    Price: 200,
    Duration: 120,
    ProviderID: 109,
    Image: "Interior-Design_1.png",
  },
  {
    ServiceID: 216,
    ServiceName: "Home Staging",
    Description: "Staging homes for sale or events",
    Category: "Interior Design",
    Price: 300,
    Duration: 180,
    ProviderID: 109,
    Image: "Home-Staging.png",
  },
  {
    ServiceID: 217,
    ServiceName: "HVAC Maintenance",
    Description: "Regular maintenance for HVAC systems",
    Category: "HVAC",
    Price: 80,
    Duration: 60,
    ProviderID: 110,
    Image: "Basic-Cleaning.png",
  },
  {
    ServiceID: 218,
    ServiceName: "Air Duct Cleaning",
    Description: "Cleaning of HVAC air ducts",
    Category: "HVAC",
    Price: 120,
    Duration: 90,
    ProviderID: 110,
    Image: "Basic-Cleaning.png",
  },
];
